context:
  version: "0.23.1"

package:
  name: openjph
  version: ${{ version }}

source:
  url: https://github.com/aous72/OpenJPH/archive/${{ version }}.tar.gz
  sha256: 8a0357075fb92feeaa36e23de78f81a869c7bb6189091cc34f41bb061c1db22b
  patches:
    # It is still difficult to use these new style tests on windows
    # https://github.com/prefix-dev/rattler-build/issues/1116
    - windows_lib_so_name.patch
    # We use too old of an stdlibc for this definition to be defined
    - fix_aarch_old_stdlibc.patch
    # https://github.com/aous72/OpenJPH/issues/198
    - 0001-Use-an-aligned-memory-allocator-for-the-memfile.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - libtiff
  run_exports:
    - ${{ pin_subpackage('openjph', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - openjph/ojph_version.h
      bin:
        - ojph_compress
        - ojph_expand
      lib:
        - openjph

about:
  homepage: https://github.com/aous72/OpenJPH
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Open source implementation of High-throughput JPEG2000 (HTJ2K).
  repository: https://github.com/aous72/OpenJPH

extra:
  recipe-maintainers:
    - hmaarrfk
